### ISSUE TITLE
[Enhancement] OBS Install for Debian Testing?

### ISSUE THREAD

**Issue by taivlam** [ungoogled-software/ungoogled-chromium-debian#229]
IIRC, I thought installs for Ungoogled Chromium on Debian Testing used to be offered on OBS during the first half of 2020.  However, after recently installing Parrot OS Home (which is based on Debian Testing), I realized I am unable to install Ungoogled Chromium because there are currently no instructions because there isn't a custom repo for Debian Testing on OBS.  (I almost made the mistake of using the Debian Sid instructions for a Debian Testing distro.)

Is it possible to enable installation of Ungoogled Chromium for distros based on Debian Testing?  Are there that I'm not aware of?  I've tried going through all of the GitHub issues but found no mention of the removal Debian Testing from OBS.

**Comment by ghost** [comment]
The closest thing we currently provide is Sid which is an alias for unstable. Unstable eventually makes it to testing from my understanding. To date there's been no demand for testing because of this. So there's a fair chance you can just use the Sid repository and it'll just work. In any case Sid is a best effort repository and not guaranteed to be working due to the nature of Sid.

We don't really provide any developmental support for Testing as there's no container images for that so if there's problems we can't readily debug the build process. But since Testing is very closely tied to Sid you should be able to build it from the Sid branch over on OBS or otherwise. We're just not going to support it at this time due to low demand. Plus it's essentially a duplication of Sid for the most part.

**Comment by ghost** [comment]
See these project links for the special Debian repositories on OBS:
https://build.opensuse.org/project/show/Debian:Next
https://build.opensuse.org/project/show/Debian:Testing
https://build.opensuse.org/project/show/Debian:Experimental

**Comment by taivlam** [comment]
> So there's a fair chance you can just use the Sid repository and it'll just work.

I've tried this and it actually worked?  I was really hesitant to try this because I didn't want to create a "franken-Debian".

(I find this a bit bizarre, because I had tried this on Parrot OS "for kicks" roughly two weeks ago, and recalled that this created some crucial missing package error in APT was only resolved after completely removing Ungoogled Chromium.  I'm not sure what has happened since then, but I can do for now is cross my fingers and hope that Ungoogled Chromium for the Debian Sid will continue to work on Parrot OS for the time being.)

Anyways, thank you for the reply.  I understand the need to be pragmatic, thus prioritizing the demands of the majority of users.
