### ISSUE TITLE
Debian Bullseye release

### ISSUE THREAD

**Issue by jorkanofaln** [ungoogled-software/ungoogled-chromium-debian#235]
Hello,
I was wondering, when ungoogled-chromium will have a package for Debian 11. Debian 11 will be released soon as a stable release.

**Comment by eLvErDe** [comment]
I tried building myself but it's not working. crashing in some python code on an assert on enum values, I have absolutely no idea what's going on :(

**Comment by Morpheus0x** [comment]
I successfully compile Chromium 90 Debian_Sid branch on Debian 11.
I installed ungoogled chromium and it worked.

How can I upload the deb files to OBS repository?

**Comment by eLvErDe** [comment]
It's not working that way :D Nobody uploads binary from untrusted source for obvious reasons.

But I think everybody would be interested in the changes made to get it built !

**Comment by Morpheus0x** [comment]
Oh ok, yea makes sense.
I haven't used OBS and find it a bit confusing.

I didn't change anything, I just built the Debian_Sid branch and everything worked.
That's probably because Bullseye is so new that basically all packages are the same and have the same version as Sid.

Could someone with access to this repo please create debian_bullseye branch from sid.
And then let OBS build for bullseye.

**Comment by mytskine** [comment]
The situation of these Debian repositories as of now (2021-09-29) has worsened:
- The Debian 10 (buster, oldstable) index has been removed.
- The Debian 11 (bullseye, stable) index does not exist yet.
- The documentation (README.md) is broken, since it uses a path `.../DebianBullseye` that does not exist on the server. 
I hope this is a transitive problem while updating this repository to the new Debian stable version. Currently, the only Debian directory is for sid (unstable): <https://download.opensuse.org/repositories/home:/ungoogled_chromium/>

BTW, the documentation currently suffers from the bad practice of globally trusting the key, instead of trusting it only for specified sources. See "The key MUST NOT be placed in /etc/apt/trusted.gpg.d" in Debian's official wiki <https://wiki.debian.org/DebianRepository/UseThirdParty>.

**Comment by ghost** [comment]
Package built successfully on testing OBS. It should be finished on the production side in the next few days.
