### ISSUE TITLE
[unified] Bookmarks and extensions are broken

### ISSUE THREAD

**Issue by tnaftali** [ungoogled-software/ungoogled-chromium-debian#245]
**Describe the bug**
When I open `chrome://bookmarks` and `chrome://extensions` I can't see anything despite having both many bookmarks and extensions.

**To Reproduce**
1. Go to `chrome://bookmarks` or `chrome://extensions`

**Screenshots**
![image](https://user-images.githubusercontent.com/8753873/137190389-2d1ce031-42f3-4eca-8d76-8f26050624db.png)

![image](https://user-images.githubusercontent.com/8753873/137190412-03b5c065-9d63-4ae6-a5c0-a1d26e9ed52e.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Debian 11 Bullseye
 - ungoogled-chromium version: Version 93.0.4577.82 (Developer Build, ungoogled-chromium) built on Debian bullseye/11, running on Debian bullseye/11 (64-bit)

**Comment by markozajc** [comment]
This is a problem with Debian's upstream: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994888

**Comment by markozajc** [comment]
Fixed in 94.0.4606.81

**Comment by tnaftali** [comment]
Hi @markozajc sorry but how can I upgrade to the fixed version from apt?

![image](https://user-images.githubusercontent.com/8753873/137728502-f99752a7-600f-4402-bdc7-1abfb95b7593.png)

**Comment by markozajc** [comment]
@tnaftali update your index with `sudo apt update`. `ungoogled-chromium` no longer depends on `-common` or `-sandbox`.
P.S. UGC 94.0.4606.81-1 is pretty broken as described in #247, you might want to stay on 93.

**Comment by pepilyser** [comment]
Hello everyone, I am on Ubuntu 20.04 Focal and I can't import my bookmarks from Mozilla Firefox. 

The thing is, as the pictures shows, that it prompts me that I need to close every Firefox windows but I don't have any. I don't even have any process from mozilla firefox.
![bookmarks_error](https://user-images.githubusercontent.com/51342296/159990043-bd85d7c4-c0ba-4643-bf3a-91c73d2be888.png)
![process_proof](https://user-images.githubusercontent.com/51342296/159990083-a4cd9698-5095-4129-b6ab-431ca93c3cba.png)

I also have a problem with extensions since they are no extensions at all showing up. 
![extensions](https://user-images.githubusercontent.com/51342296/159990393-439fddc6-3920-4efe-b1df-0c1eb969afeb.png)
 
So this issue was exactly about the problems I have but there is no real solution in here, so if anyone has an idea, I would gladly take it.

**Comment by ghost** [comment]
This appears to be fixed in latest release.
