### ISSUE TITLE
How to uninstall ungoogled chromium installed with curl

### ISSUE THREAD

**Issue by danzankul** [ungoogled-software/ungoogled-chromium-debian#267]
Hi I am using ubuntu 20.04 and I installed ungoogled chromium via curl https://ungoogled-chromium.run | bash method because I do not have snap, as explained  at https://github.com/Joffreybvn/ungoogled-chromium-snapcraft.
Now, since ANY link is blocked by this chromium release and I can't use such browser (I won't get crazy to workaround such issue) I'm in trouble because I do not find a way to uninstall it. Any help?

**Comment by markozajc** [comment]
I don't follow. `https://ungoogled-chromium.run/` installs the snap version, which has nothing to do with this repository. Do you mean that since you can't use it you're using this? In such case, see #247 and below for further discussion on the hang issue.

The current workaround is to use the unportable version by Eloston at https://github.com/Eloston/ungoogled-chromium-binaries (the prebuilt binaries seem to be built for Debian Bullseye, so you might have to build it yourself if they don't work on your system).

To get it, create a new directory (call it whatever you want), and download the following files into it:
- [ungoogled-chromium-common](https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1.unportable1/ungoogled-chromium-common_95.0.4638.69-1.unportable1_amd64.deb)
- [ungoogled-chromium-driver](https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1.unportable1/ungoogled-chromium-driver_95.0.4638.69-1.unportable1_amd64.deb)
- [ungoogled-chromium-sandbox](https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1.unportable1/ungoogled-chromium-sandbox_95.0.4638.69-1.unportable1_amd64.deb)
- [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1.unportable1/ungoogled-chromium_95.0.4638.69-1.unportable1_amd64.deb)

Then open up a terminal, cd into the directory you created, and install the deb files with `sudo apt install ./*.deb`. If this fails, or if ungoogled chromium doesn't work afterwards, you'll have to compile it yourself (I haven't yet tried building the unportable branch, but you might be able to get help from Eloston).

**Comment by markozajc** [comment]
This issue is related to the snap version of ungoogled chromium, not the debian one. Here's the solution nevertheless:
```bash
sudo snap remove ungoogled-chromium
```
