### ISSUE TITLE
Request for update to version: 99.0.4844.51-1.1 for Ubuntu

### ISSUE THREAD

**Issue by joelbschwartz** [ungoogled-software/ungoogled-chromium-debian#290]
Hello, I am currently using the available version of 95.0.4638.54-1 for Ubuntu_Focal, but there is at least one error with this version that prevents me from properly using the Serial API.

I can open a serial port. When I attempt to write to the port, only the first write is successful. Nothing happens for subsequent writes. When I close the port, the unsent writes are flushed through.

Is there an estimate for when this updated version might be available on openSUSE?

Thank you!

**Comment by Kwaskoff** [comment]
We need update with security patch! https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-1096
‼️Attention‼️

**Comment by mpaunovic** [comment]
AppImage:

https://github.com/clickot/ungoogled-chromium-binaries/releases/latest

Flatpak:

https://flathub.org/apps/details/com.github.Eloston.UngoogledChromium

It's not a perfect solution, but it's the best one we have.

**Comment by Ph0rk0z** [comment]
What nobody seems to answer, which version did the vulnerability start in?

**Comment by networkException** [comment]
> What nobody seems to answer

The current debian maintainer is not really active at the moment

> which version did the vulnerability start in?

I don't think thats revealed yet

**Comment by berkley4** [comment]
Since there aren't any v99 deb package builds available atm and there's a nasty exploit out there, people are welcome to try my own personal build of 99.0.4844.84. It's built on debian stable (like unportable) and hence should work on debian and probably ubuntu focal (not sure about opensuse).

https://github.com/berkley4/ungoogled-chromium-debian/releases

**Comment by mpaunovic** [comment]
berkley4, would you be by any chance interested in becoming the new Debian/Ubuntu maintainer? We desperately need one.

No disrespect to braewoods, just stating the obvious.

There, I said it.

**Comment by berkley4** [comment]
> berkley4, would you be by any chance interested in becoming the new Debian/Ubuntu maintainer? We desperately need one.
> 
> No disrespect to braewoods, just stating the obvious.
> 
> There, I said it.

I'm not sure about becoming maintainer, not least because I doubt the automated build system could handle building my branch, which uses a full git clone of chromium (its post-build size is currenly 71GiB). I'd be a bit lost using the automated build service too, something that Braewoods seems a lot more knowledgeable about.

However, I could see about getting my debs included on the [ungoogled-chromium-binaries](https://ungoogled-software.github.io/ungoogled-chromium-binaries/) page.

**Comment by berkley4** [comment]
If anyone's interested, I've just uploaded 100.0.4896.75-1 to the link I posted (a few posts above this one).

**Comment by mpaunovic** [comment]
Thank you!

More people should know about your builds.

**Comment by berkley4** [comment]
Edit: Full release is here - [100.0.4896.127-1](https://github.com/berkley4/ungoogled-chromium-debian/releases/tag/100.0.4896.127-1)

<del>There's yet another zero-day vulnerability in chromium which is being actively exploited, so here's [100.0.4896.127](https://github.com/berkley4/ungoogled-chromium-debian/releases/tag/100.0.4896.127-pre1) for those that are interested.<del>

<del>Upstream ungoogled hasn't been updated yet, but the last release's patches apply without modification, hence the pre-release label.<del>

**Comment by mpaunovic** [comment]
How can your builds become more accessible to users? Maybe a pinned issue, the binaries page or PPA perhaps? I'm not sure many people know about them and that's a real shame.

**Comment by berkley4** [comment]
When I get some spare time I plan on seeing if they can be hosted on the ungoogled-chromium-binaries page.

Before I do that I'd like to resurrect building from a tarball download (instead of git). This would make it more accessible to others who want to do their own builds, and perhaps automated builds too.

**Comment by berkley4** [comment]
[101.0.4951.41-1](https://github.com/berkley4/ungoogled-chromium-debian/releases/tag/101.0.4951.41-1) has been uploaded.
