### ISSUE TITLE
Urgently update to version: 99.0.4844.84-1 for Ubuntu

### ISSUE THREAD

**Issue by Kwaskoff** [ungoogled-software/ungoogled-chromium-debian#291]
Everybody is in dangerous, because is CVE-2022-1096

https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-1096

**Comment by JamesClarke7283** [comment]
+1
I actually think building of the browser should be done automatically for the repo if not done already. Browsers are literally programs which arbitrarily run code from the web in a weak sandbox(if JavaScript is enabled).

I think this issue should be pinned also, because i only found  this out when i experienced #303 and came here to see what was going on. It hasn't been updated for 8+ months for Focal, and the other Debian based ones are about that. The fedora packaging looks like the fedora one was more recently updated and uses version 98, but that is still too outdated.
[https://download.opensuse.org/repositories/home:/ungoogled_chromium/Fedora_35/x86_64/](https://download.opensuse.org/repositories/home:/ungoogled_chromium/Fedora_35/x86_64/)

It appears there are issues with even upgrading to version 94 for certain Debian versions as shown in this issue #247
