### ISSUE TITLE
unportable-branch: confused with README.md

### ISSUE THREAD

**Issue by jolly-jump** [ungoogled-software/ungoogled-chromium-debian#293]
Hi @Eloston ,

I am desperately trying to repeat the compiling steps in this unportable branch where your latest working debian/ubuntu binary package seems to stem from.

There are somethings off in the README.md: 
- it says, "Tested on Debian 10 (buster). It will not work on newer Debian versions right now because python-xcbgen is not available on them (only python3-xcbgen)." - so I tried using buster. But there are so many packages that cannot be installed although they seem to be needed, I will quote a few from the mk-build-deb - step:
```
dpkg -i ungoogled-chromium-build-deps_99.0.4844.51-1.unportable1_all.deb
...
dpkg: dependency problems prevent configuration of ungoogled-chromium-build-deps:
  Package python-is-python3 is not installed.
 ungoogled-chromium-build-deps depends on node-typescript (>= 4.4.3); however:
  Version of node-typescript on system is 3.3.3333-1.
 ungoogled-chromium-build-deps depends on terser | uglifyjs.terser; however:
  Package terser is not installed.
  Package uglifyjs.terser is not installed.
 ungoogled-chromium-build-deps depends on libpipewire-0.3-dev; however:
  Package libpipewire-0.3-dev is not installed.
```

Then there is the `build.sh` file which seems to another script making the life easier, but it seems it is advisable to set some environment variables  (LLVM_VERSION=14 ? use python3 ?)... or maybe the "buster" advise is not so good after all...

Then there are your TODO notes in the end of the Readme which don't help me (or at least make it even more confusing).

Is there a chance you could provide some hints what your current steps are to compile the beast?

Thanks in advance.

**Comment by ghost** [comment]
@jolly-jump I build this on sid. I ignore the advice to use buster, I think it's stale and should have been removed.
Since the last commit updates the required LLVM to 14, it seems like this can only build on sid at the moment, anyway.
The exact steps I follow:

1. make a sid chroot
2. (root) apt install git python3 packaging-dev equivs
3. (unprivileged) git clone https://github.com/ungoogled-software/ungoogled-chromium-debian.git
4. cd ungoogled-chromium-debian/
5. git switch unportable
6. git submodule update --init
7. cd ungoogled-chromium
8. git switch master
9. cd ..
10. debian/scripts/setup debian
11. mk-build-deps
12. (root) install the build deps
13. (unprivileged) debian/scripts/setup local-src
14. dpkg-buildpackage -b -uc

works very smoothly

**Comment by jolly-jump** [comment]
Hi @gadall ,

thanks a lot. That makes totally sense.
I think I had figured out the steps 1-14 except 6-9 after writing my issue, so this confirms I am on a working track.
Two follow-up questions: 
- is it necessary in the build-process to do it as an unprivileged user? Since I am working with a docker-container I'd rather use root all the time, but I can change my workflow, if it is necessary (that it would be good practice I understand)
- does the `git submodule update --init` step and the `git switch master` step determine which version of ungoogled-chromium upstream I am compiling?

Anyway, code is compiling using debian/bullseye and LLVM-14 (from apt.llvm.org), **except** for all the dependencies that came with the node-typescript  requirement coming from testing. So basically libc(-dev), elf-stuff and these kinds are all from testing, while the rest is from stable.
If this does not work out, I'll change to sid completely.

Thanks again!

**Comment by ghost** [comment]
- steps 6-9 are just because they don't always update the submodule but we can do it ourselves
- i don't think it's really necessary to make an unprivileged user, as you say in a container, but it's kind of a "good habit" and occasionally a script will actually warn you that you're root when you "shouldn't" be, so it's just an acquired habit.
- the submodule update actually pulls in the content, but at the committed commit (currently 9c6f29c). You can switch to the latest (master) if it's ahead. Yes, that determines the version of ungoogled-chromium

Try maybe this:
In /etc/apt/preferences.d/limit-testing

Package: *
Pin: release a=testing
Pin-Priority: 150

This way, when you install a package from testing, like: apt-get install node-typescript/testing, it explicitly specifies that node-typescript should come from testing but all other packages will come from stable if possible. This can help you stick more closely to stable. And this can matter if your resulting ungoogled-chromium package ends up depending on a package version not in stable.

**Comment by ghost** [comment]
@jolly-jump You can usually update to a later patch version of the same major Chromium version with no other changes, but for example at the moment ungoogled-chromium's master is already at Chromium 100 and unportable is at 99 so you can switch to the latest 99 commit but not master.

**Comment by jolly-jump** [comment]
@gadall 
Ok, thanks 
- apt-pinning is what I did already, thanks.
- ok, I see your point about the versions in the cascading git repos.

To not further confuse the situation, but at least it should be mentioned: There is the ticket: https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/issues/127 which is quite right about the amount of confusing potential.
But I admit that the fork of @berkley4 does look quite up-to-date. So I guess I will give it a try as well.

As long as there are no big steps, like merging berkley4s and @braewoods s tree and making unportablelinux obsolete again, I guess your list above should suffice to help others like it did for me. 

cheers!

**Comment by jolly-jump** [comment]
@gadall 
Thanks. I got ungoogled-chromium_99.0.4844.51-1.unportable1_amd64.deb
to compile finally using this unportable-branch.

- I was - on the other hand - not yet successful in compiling a binary using berkley4 s ansatz, the downloadable binaries are not ubuntu compatible either.
- neither was I proficient enough to understand how to compile ungoogled-chromium-portablelinux directly for r within ubuntu.

This is better than nothing. 
Thanks again!
