### ISSUE TITLE
 keepassxc-browser won't connect to KeepassXC

### ISSUE THREAD

**Issue by bloatmode** [ungoogled-software/ungoogled-chromium-debian#75]
I'm running Ubuntu 18.04 LTS, and I installed both ungoogled-chromium and keepassxc-browser from your [PPA](https://launchpad.net/~braewoods/+archive/ubuntu/ungoogled-chromium?field.series_filter=bionic).
Keepass-XC was installed from the official [PPA](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc).

I'm getting the following error when clicking on the extension's icon:
>Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

Trying to connect from the extension's settings won't work either. Integration is enabled for all browsers in KeepassXC's settings, and the extension works just fine in Firefox (there, it was installed from [addons.mozilla.org](https://addons.mozilla.org/)).

One thing I noticed which could be the cause of the issue is that when using Firefox I can see that the process keepassxc-proxy is running, while when using Ungoogled Chromium it's not. I checked it because it was mentioned in the [troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

I'm reporting the issue here because that's what the PPA description said to do.

**Comment by ghost** [comment]
Good find. I hadn't yet tested it myself as I don't often use chromium lately. I have traced the issue to a permissions issue. It seems the extension ID is different for this case where the extension is unpacked.

You can workaround the issue temporarily by adding the extension ID to the `~/.config/chromium/NativeMessagingHosts/.org.keepassxc.keepassxc_browser.json` file's allowed_origins array but the real fix will be to the keepassxc source code. I will see what I can work out with them.

**Comment by ghost** [comment]
In the meantime I will apply the patch I have come up with to my own build of keepassxc. You can use it if you wish but that is up to you.

**Comment by bloatmode** [comment]
Can't you just set the extension ID appropriately in the appropriate file in your keepassxc-browser package?

**Comment by ghost** [comment]
No. You can't set the extension ID directly from the extension itself. It's generated by Chromium using an algorithm that involves hashing the directory name that the extension is in. So the only real solution is to update keepassxc with the new ID.

It deviates from the original extension ID because it is provided as an unpacked extension instead of as a crx bundle. Their IDs are generated differently and I do not think I could get the unpacked extension to produce the same ID. And I know of no way to get Chromium to load an extension from an external file instead of an external directory.

**Comment by ghost** [comment]
So upstream has rejected the patch because the "unpacked extension ID is unique". It seems consistent across different chromium versions in my packaging so what I am going to do is just provide a patched version of keepassxc in the ungoogled-chromium PPA so people can have both in sync and have them work together properly. It should be available to you shortly. That should resolve the issue for you.

**Comment by bloatmode** [comment]
> No. You can't set the extension ID directly from the extension itself.

This is not what I meant. I'm not familiar with how packaging works in Ubuntu, but couldn't you make your install script edit `~/.config/chromium/NativeMessagingHosts/.org.keepassxc.keepassxc_browser.json` when installing package keepassxc-browser?

**Comment by ghost** [comment]
Yes though that has practical problems because home directories are at variable locations. Even if there weren't packaging challenges there's still the problems I observed in testing keepassxc integration. keepassxc deletes or overwrites the browser integration files like `org.keepassxc.keepassxc_browser.json` whenever the browser integration settings are saved or otherwise modified regardless of the nature of the changes.

So even if I fixed it in the packaging for the extension keepassxc would just undo them taking us back to the original problem. The only viable solution seems to be to patch keepassxc so the extension ID is included in the generated configuration since manual configuration seems to be out of the question as keepassxc will modify or remove it effectively undoing the manual configuration.

**Comment by ghost** [comment]
Ok, it's done. You can install the patched keepassxc from the PPA now. My tests reveal that it should now connect properly.

**Comment by ghost** [comment]
@Eloston please close this issue. I believe it has been resolved.
