### ISSUE TITLE
Create ubuntu_focal branch (may want to wait until release)

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-debian#90]
I thought I would leave this as a reminder that we will need a branch for ubuntu_focal in the near future.

**Comment by marksolaris** [comment]
I'm using this recipe to compile on focal

https://github.com/Eloston/ungoogled-chromium/issues/978

**Comment by ghost** [comment]
I'll get started prototyping a new branch for focal after the beta freeze (April 2nd). That should give enough time to have it ready by launch day.

**Comment by marksolaris** [comment]
There's a gotcha with focal/recent Chromiums, either the Intel GPU mesa device drivers aren't there yet, or it's the xrandr changes that are plaguing window managers right now. They have my build showing blank white ungoogled-chrome windows when displaying to another bionic host. It renders OK locally on the focal host, but set the $DISPLAY to the bionic and the window shows blank white for any content inside the chromium window.

A workaround: Run Xnest on the focal, displayed to the bionic, and the ungoogled-chromium displays OK inside the Xnest but is super slow of course.

This one is hard to pin down, but I'm going for the mesa drivers being the culprit.

Edit: This issue is mentioned here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1064593&q=X11%20blank&can=2

**Comment by Eloston** [comment]
FYI I pushed a new `ubuntu_focal` branch that points to the current tip of `debian_sid`.

**Comment by ghost** [comment]
Ok. I'm trying to build debian_sid with Clang 10 before Focal gets serious.

**Comment by marksolaris** [comment]
Saying goodbye to this package and re-testing
```
xserver-xorg-video-intel/focal,now 2:2.99.917+git20190815-1 amd64 [installed,automatic]
  X.Org X server -- Intel i8xx, i9xx display driver
```
https://launchpad.net/ubuntu/focal/+package/xserver-xorg-video-intel
```
The use of this driver is discouraged if your hw is new enough (ca.
 2007 and newer). You can try uninstalling this driver and let the
 server use its builtin modesetting driver instead.
```

Nope, no change, when remote viewed on a 18.04 X11 it's still a blank white window with unrendered but active HTML elements.

Note I doubt this is ungoogled-chromium's fault, but noting it here for the google.
